---
micronaut:
  application:
    name: user-list

---


datasources:
  default:
    url: jdbc:postgresql://172.22.0.2:5432/blog?connectTimeout=10&socketTimeout=40
    username: blog
    password: blogPazZw0rd
    maxSize: 5
    dialect: POSTGRES


---
micronaut:
  router:
    static-resources:
      default:
        enabled: true   #<1>
        mapping: "/**"  #<2>
        paths: "classpath:public" #<3>